version: '3.8'

services:
  Squid_1:
    image: pmohan/squid_2020:template_v_UTC
    ports:
      - target: 3128
        published: 3128
        protocol: tcp
        mode: host
      - target: 3130
        published: 3130
        protocol: udp
        mode: host
    configs:
      - source: squid_config_1
        target: /etc/squid/squid.conf
      - source: hosts_CF_v1
        target: /etc/hosts
      - source: resolver
        target: /etc/resolv.conf
    deploy:
      mode: replicated
      replicas: 4
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
  cadvisor03:
     image: google/cadvisor:latest
     ports:
       - 8089:8080
     volumes:
       - /:/rootfs:ro
       - /var/run:/var/run:rw
       - /sys:/sys:ro
       - /var/lib/docker/:/var/lib/docker:ro
     deploy:
          placement:
            constraints:
              - node.hostname == prod-vl-dockersquid01.sbetprod.ads
  cadvisor04:
     image: google/cadvisor:latest
     ports:
       - 8090:8080
     volumes:
       - /:/rootfs:ro
       - /var/run:/var/run:rw
       - /sys:/sys:ro
       - /var/lib/docker/:/var/lib/docker:ro
     deploy:
          placement:
            constraints:
              - node.hostname == prod-vl-dockersquid02.sbetprod.ads
  cadvisor05:
     image: google/cadvisor:latest
     ports:
       - 8091:8080
     volumes:
       - /:/rootfs:ro
       - /var/run:/var/run:rw
       - /sys:/sys:ro
       - /var/lib/docker/:/var/lib/docker:ro
     deploy:
          placement:
            constraints:
              - node.hostname == prod-vl-dockersquid03.sbetprod.ads
  cadvisor06:
     image: google/cadvisor:latest
     ports:
       - 8092:8080
     volumes:
       - /:/rootfs:ro
       - /var/run:/var/run:rw
       - /sys:/sys:ro
       - /var/lib/docker/:/var/lib/docker:ro
     deploy:
          placement:
            constraints:
              - node.hostname == prod-vl-dockersquid04.sbetprod.ads
configs:
  squid_config_1:
    file: ./squid.conf
  hosts_CF_v1:
    file: ./hosts
  resolver:
    file: ./resolv.conf

