version: '3.8'

services:
  Squid_2:
    image: pmohan/squid_2020:template_v_UTC
    ports:
      - target: 3128
        published: 3129
        protocol: tcp
        mode: host
      - target: 3130
        published: 3131
        protocol: udp
        mode: host
    configs:
      - source: squid_config_2
        target: /etc/squid/squid.conf
      - source: hosts_CF_v2
        target: /etc/hosts
      - source: resolver
        target: /etc/resolv.conf
    deploy:
      mode: replicated
      replicas: 4
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
configs:
  squid_config_2:
    file: ./squid_pool2.conf
  hosts_CF_v2:
    file: ./hosts
  resolver:
    file: ./resolv.conf

